import type { ReadingTest } from "@/lib/content/types";

/**
 * Additional original GT Reading practice tests. All passages and questions are
 * original, copyright-free, and written in the IELTS General Training style.
 * Every accepted answer is supported by the passage text.
 */
const rawReadingTests: ReadingTest[] = [
  {
    id: "gt-reading-002",
    skill: "reading",
    variant: "general-training",
    title: "GT Reading Practice — The Return of the Night Train",
    timeMinutes: 20,
    sections: [
      {
        id: "s1",
        name: "Section 3: General Reading",
        passageTitle: "The Return of the Night Train",
        passageParagraphs: [
          "For much of the twentieth century, sleeper trains were a common way to travel long distances across Europe. Passengers would board in the evening, sleep in a private cabin or a shared couchette, and wake up the next morning in a distant city. As cheap flights spread in the 1990s, many of these services were cut, and by 2010 only a handful remained.",
          "In recent years, however, the night train has made a surprising comeback. The main reason is concern about the environment. A short flight produces far more carbon dioxide per passenger than the same journey by rail, and a growing number of travellers now choose the train precisely to reduce their impact. Several European governments have supported this shift by funding new routes and modern carriages.",
          "Comfort has also improved. New sleeper carriages offer reading lights, power sockets and, in the more expensive cabins, a private shower. Supporters argue that a night train saves the cost of a hotel and turns travelling time into sleeping time, so passengers arrive rested and ready for the day.",
          "There are still difficulties. Running a sleeper service is expensive, because each train carries fewer passengers than a daytime one and needs extra staff. Tickets can therefore cost more than a budget flight. Even so, bookings have risen steadily, and railway companies are ordering new carriages to meet the demand.",
        ],
        questions: [
          { id: "q1", number: 1, type: "true_false_notgiven",
            prompt: "Sleeper trains were rarely used in Europe before the year 2000.",
            accepted: ["false"] },
          { id: "q2", number: 2, type: "true_false_notgiven",
            prompt: "The growth of cheap flights led to many sleeper services being cut.",
            accepted: ["true"] },
          { id: "q3", number: 3, type: "true_false_notgiven",
            prompt: "All new sleeper cabins now include a private shower.",
            accepted: ["false"] },
          { id: "q4", number: 4, type: "true_false_notgiven",
            prompt: "Some European governments have paid for new night-train routes.",
            accepted: ["true"] },
          { id: "q5", number: 5, type: "sentence_completion", wordLimit: 1,
            prompt: "The main reason for the night train's return is concern about the ______.",
            accepted: ["environment"] },
          { id: "q6", number: 6, type: "sentence_completion", wordLimit: 2,
            prompt: "Compared with rail, a short flight produces far more ______ per passenger.",
            accepted: ["carbon dioxide", "CO2"] },
          { id: "q7", number: 7, type: "single_choice",
            prompt: "According to the passage, one advantage of a night train is that it:",
            options: [
              { value: "A", label: "is always cheaper than flying" },
              { value: "B", label: "saves the cost of a hotel" },
              { value: "C", label: "carries more passengers than a day train" },
            ],
            accepted: ["B"] },
          { id: "q8", number: 8, type: "single_choice",
            prompt: "Running a sleeper service is expensive partly because it:",
            options: [
              { value: "A", label: "needs extra staff" },
              { value: "B", label: "uses older carriages" },
              { value: "C", label: "travels more slowly" },
            ],
            accepted: ["A"] },
          { id: "q9", number: 9, type: "short_answer", wordLimit: 3,
            prompt: "What are railway companies ordering to meet the rising demand?",
            accepted: ["new carriages"] },
        ],
      },
    ],
  },
  {
    id: "gt-reading-003",
    skill: "reading",
    variant: "general-training",
    title: "GT Reading Practice — Urban Beekeeping",
    timeMinutes: 20,
    sections: [
      {
        id: "s1",
        name: "Section 3: General Reading",
        passageTitle: "Urban Beekeeping",
        passageParagraphs: [
          "Keeping bees was once an activity associated with the countryside, but in the last twenty years it has become increasingly popular in cities. Rooftops, balconies and community gardens across the world now house hives, and some hotels and offices keep bees to produce their own honey.",
          "Cities can be surprisingly good places for bees. Parks, street trees and private gardens provide a wide variety of flowers, often over a longer season than in farmland, where a single crop may flower for only a few weeks. Because city plants are rarely sprayed with the strong chemicals used on large farms, urban bees may also be exposed to fewer harmful substances.",
          "Beekeepers say the hobby brings many rewards. Besides honey, bees help to pollinate fruit and vegetables grown nearby, improving local harvests. Caring for a hive also teaches patience and a respect for nature, and many keepers describe watching their bees as relaxing.",
          "Experts warn, however, that beekeeping should not be seen as a simple way to 'save the bees'. Honeybees kept in hives are not endangered; it is many species of wild bee that are in trouble. If too many hives are placed in one area, the kept bees may compete with wild ones for food. The best way to help all bees, specialists say, is to plant a wide range of flowers and avoid using pesticides.",
        ],
        questions: [
          { id: "q1", number: 1, type: "true_false_notgiven",
            prompt: "Urban beekeeping has grown more popular over the past two decades.",
            accepted: ["true"] },
          { id: "q2", number: 2, type: "true_false_notgiven",
            prompt: "Some offices keep bees in order to make their own honey.",
            accepted: ["true"] },
          { id: "q3", number: 3, type: "true_false_notgiven",
            prompt: "City bees are usually exposed to more chemicals than bees on large farms.",
            accepted: ["false"] },
          { id: "q4", number: 4, type: "yes_no_notgiven",
            prompt: "The writer believes keeping honeybees is the best way to save endangered bees.",
            accepted: ["no"] },
          { id: "q5", number: 5, type: "sentence_completion", wordLimit: 2,
            prompt: "In farmland, a single ______ may flower for only a few weeks.",
            accepted: ["crop"] },
          { id: "q6", number: 6, type: "sentence_completion", wordLimit: 1,
            prompt: "Bees help to ______ fruit and vegetables grown nearby.",
            accepted: ["pollinate"] },
          { id: "q7", number: 7, type: "single_choice",
            prompt: "According to experts, a problem with placing too many hives in one area is that:",
            options: [
              { value: "A", label: "the honey tastes worse" },
              { value: "B", label: "kept bees compete with wild bees for food" },
              { value: "C", label: "the bees become more aggressive" },
            ],
            accepted: ["B"] },
          { id: "q8", number: 8, type: "short_answer", wordLimit: 3,
            prompt: "Besides planting many flowers, what do specialists say people should avoid using?",
            accepted: ["pesticides", "using pesticides"] },
        ],
      },
    ],
  },
  {
    id: "gt-reading-004",
    skill: "reading",
    variant: "general-training",
    title: "GT Reading Practice — The Power Nap",
    timeMinutes: 20,
    sections: [
      {
        id: "s1",
        name: "Section 3: General Reading",
        passageTitle: "The Power Nap",
        passageParagraphs: [
          "A short daytime sleep, often called a 'power nap', has long been popular in many cultures. In some countries a rest after lunch is a normal part of the day. Recently, scientists have begun to study these naps carefully, and their findings suggest that a brief sleep can genuinely improve how we think and feel.",
          "Research indicates that the ideal length for a nap is between ten and twenty minutes. A nap of this length can increase alertness and improve mood without leaving the sleeper feeling groggy. If a nap lasts much longer, the body enters a deeper stage of sleep, and waking from it can produce a heavy, confused feeling that may last for some time.",
          "Timing matters too. Experts recommend napping in the early afternoon, when many people naturally feel a dip in energy. Napping too late in the day can make it harder to fall asleep at night. For this reason, a nap should not be treated as a replacement for a good night's sleep, but as a useful addition to it.",
          "Some companies have responded to this research by providing quiet rooms where staff can rest. They argue that a short nap improves concentration and reduces mistakes in the afternoon, so the time is well spent. Not everyone agrees, and in many workplaces sleeping during the day is still frowned upon.",
        ],
        questions: [
          { id: "q1", number: 1, type: "true_false_notgiven",
            prompt: "Daytime napping is a recent habit that did not exist in the past.",
            accepted: ["false"] },
          { id: "q2", number: 2, type: "true_false_notgiven",
            prompt: "Scientists have found that a brief nap can improve how people think.",
            accepted: ["true"] },
          { id: "q3", number: 3, type: "true_false_notgiven",
            prompt: "Every company now provides rooms where employees can sleep.",
            accepted: ["false"] },
          { id: "q4", number: 4, type: "sentence_completion", wordLimit: 3,
            prompt: "Research suggests the ideal nap lasts between ______ minutes.",
            accepted: ["ten and twenty", "10 and 20"] },
          { id: "q5", number: 5, type: "sentence_completion", wordLimit: 1,
            prompt: "A nap that is too long can leave the sleeper feeling ______.",
            accepted: ["groggy"] },
          { id: "q6", number: 6, type: "single_choice",
            prompt: "Experts recommend napping in the early afternoon because:",
            options: [
              { value: "A", label: "it is the warmest part of the day" },
              { value: "B", label: "many people naturally feel a dip in energy then" },
              { value: "C", label: "it is when most people finish work" },
            ],
            accepted: ["B"] },
          { id: "q7", number: 7, type: "single_choice",
            prompt: "The writer says a nap should be seen as:",
            options: [
              { value: "A", label: "a replacement for night-time sleep" },
              { value: "B", label: "an addition to a good night's sleep" },
              { value: "C", label: "a cure for serious sleep problems" },
            ],
            accepted: ["B"] },
          { id: "q8", number: 8, type: "short_answer", wordLimit: 4,
            prompt: "According to some companies, what does a short nap reduce in the afternoon?",
            accepted: ["mistakes", "mistakes in the afternoon"] },
        ],
      },
    ],
  },
  {
    id: "gt-reading-005",
    skill: "reading",
    variant: "general-training",
    title: "GT Reading Practice — The Rise of the Audiobook",
    timeMinutes: 20,
    sections: [
      {
        id: "s1",
        name: "Section 3: General Reading",
        passageTitle: "The Rise of the Audiobook",
        passageParagraphs: [
          "Listening to a story being read aloud is one of the oldest forms of entertainment, but the modern audiobook is a recent invention. Early recorded books were sold on cassette tapes and later on compact discs, mainly for people who found reading print difficult. The arrival of smartphones changed everything, allowing listeners to carry an entire library in their pocket.",
          "Today audiobooks are one of the fastest-growing parts of publishing. Many listeners enjoy them while doing something else, such as driving, exercising or cooking. Because of this, audiobooks have brought stories to people who say they simply do not have time to sit down and read.",
          "The quality of the recordings has improved greatly. Famous actors are often hired to narrate, and a skilled reader can bring a book to life by giving each character a different voice. Some productions even add music and sound effects, making the experience closer to radio drama than to silent reading.",
          "Not everyone is convinced that listening is the same as reading. Critics argue that it is easier to lose concentration while listening, and that a listener cannot easily turn back to reread a difficult passage. Supporters reply that, whichever method is used, the important thing is that more people are enjoying books than ever before.",
        ],
        questions: [
          { id: "q1", number: 1, type: "true_false_notgiven",
            prompt: "The earliest recorded books were sold on compact discs.",
            accepted: ["false"] },
          { id: "q2", number: 2, type: "true_false_notgiven",
            prompt: "Smartphones made it possible for listeners to carry many books with them.",
            accepted: ["true"] },
          { id: "q3", number: 3, type: "true_false_notgiven",
            prompt: "Audiobooks are now one of the fastest-growing parts of publishing.",
            accepted: ["true"] },
          { id: "q4", number: 4, type: "sentence_completion", wordLimit: 2,
            prompt: "Early recorded books were sold mainly for people who found reading ______ difficult.",
            accepted: ["print"] },
          { id: "q5", number: 5, type: "sentence_completion", wordLimit: 2,
            prompt: "Some productions add music and ______ to the recording.",
            accepted: ["sound effects"] },
          { id: "q6", number: 6, type: "single_choice",
            prompt: "Many people listen to audiobooks while:",
            options: [
              { value: "A", label: "sleeping" },
              { value: "B", label: "doing another activity such as driving" },
              { value: "C", label: "writing reviews" },
            ],
            accepted: ["B"] },
          { id: "q7", number: 7, type: "single_choice",
            prompt: "One criticism of audiobooks mentioned in the passage is that:",
            options: [
              { value: "A", label: "they are too expensive" },
              { value: "B", label: "it is easier to lose concentration" },
              { value: "C", label: "the narrators are not skilled" },
            ],
            accepted: ["B"] },
          { id: "q8", number: 8, type: "short_answer", wordLimit: 2,
            prompt: "Who are often hired to narrate modern audiobooks?",
            accepted: ["actors", "famous actors"] },
        ],
      },
    ],
  },
  {
    id: "gt-reading-006",
    skill: "reading",
    variant: "general-training",
    title: "GT Reading Practice — Repair Cafés",
    timeMinutes: 20,
    sections: [
      {
        id: "s1",
        name: "Section 3: General Reading",
        passageTitle: "Repair Cafés",
        passageParagraphs: [
          "A repair café is a free meeting place where people bring broken household items and fix them with the help of volunteers. Visitors might arrive with a wobbly chair, a toaster that no longer heats, or a torn jacket. Alongside tools and spare parts, the café offers coffee and a friendly atmosphere, which is how it gets its name.",
          "The first repair café was held in the Netherlands in 2009. The idea spread quickly, and there are now thousands of them in dozens of countries. Most are run entirely by volunteers, and many take place once a month in a community hall or library.",
          "The aim is partly practical and partly environmental. Many modern products are thrown away as soon as they stop working, even when the fault is small and easy to mend. By repairing these items, the cafés reduce waste and save visitors money. Organisers also hope to keep alive skills, such as sewing and basic electronics, that fewer people now learn at home.",
          "Importantly, repair cafés do not simply fix things for people; they encourage visitors to take part. A volunteer will often work alongside the owner, explaining what has gone wrong and showing how to put it right. In this way, people leave not only with a working object but also with new confidence to try repairs themselves.",
        ],
        questions: [
          { id: "q1", number: 1, type: "true_false_notgiven",
            prompt: "Visitors must pay a fee to have their items repaired.",
            accepted: ["false"] },
          { id: "q2", number: 2, type: "true_false_notgiven",
            prompt: "The first repair café was held in the Netherlands.",
            accepted: ["true"] },
          { id: "q3", number: 3, type: "true_false_notgiven",
            prompt: "Most repair cafés are run by paid professionals.",
            accepted: ["false"] },
          { id: "q4", number: 4, type: "true_false_notgiven",
            prompt: "Repair cafés are now found in many different countries.",
            accepted: ["true"] },
          { id: "q5", number: 5, type: "sentence_completion", wordLimit: 1,
            prompt: "The café is named partly after the ______ it offers along with repairs.",
            accepted: ["coffee"] },
          { id: "q6", number: 6, type: "sentence_completion", wordLimit: 2,
            prompt: "By repairing items, the cafés reduce ______ and save visitors money.",
            accepted: ["waste"] },
          { id: "q7", number: 7, type: "single_choice",
            prompt: "One aim of repair cafés is to keep alive skills such as:",
            options: [
              { value: "A", label: "cooking and gardening" },
              { value: "B", label: "sewing and basic electronics" },
              { value: "C", label: "painting and drawing" },
            ],
            accepted: ["B"] },
          { id: "q8", number: 8, type: "single_choice",
            prompt: "What do repair cafés encourage visitors to do?",
            options: [
              { value: "A", label: "watch the volunteers work" },
              { value: "B", label: "take part in the repair" },
              { value: "C", label: "buy new tools" },
            ],
            accepted: ["B"] },
        ],
      },
    ],
  },
  {
    id: "gt-reading-007",
    skill: "reading",
    variant: "general-training",
    title: "GT Reading Practice — Wildlife Corridors",
    timeMinutes: 20,
    sections: [
      {
        id: "s1",
        name: "Section 3: General Reading",
        passageTitle: "Wildlife Corridors",
        passageParagraphs: [
          "As towns, farms and roads spread across the land, the natural areas where animals live are often broken into small, separated pieces. An animal that needs a large territory may find itself trapped in a patch of forest too small to support it. A wildlife corridor is a strip of natural habitat that connects two such patches, allowing animals to move safely between them.",
          "Corridors can take many forms. Some are simply lines of trees and bushes left along a river or field edge. Others are far more ambitious: in several countries, special bridges covered with grass and plants have been built over busy motorways so that deer and other animals can cross without danger. Tunnels under roads serve the same purpose for smaller creatures.",
          "The benefits are clear. By linking habitats, corridors give animals access to more food and a wider choice of mates, which keeps populations healthy. They also allow species to move to cooler areas as the climate warms. Without such routes, isolated groups of animals can weaken over time and may eventually disappear.",
          "Building corridors is not always easy. Land is expensive, and a corridor may need the agreement of many different owners. Yet conservationists argue that the cost is small compared with the value of the wildlife saved, and a growing number of governments now include corridors in their plans for new roads and developments.",
        ],
        questions: [
          { id: "q1", number: 1, type: "true_false_notgiven",
            prompt: "The spread of roads and farms can divide natural areas into smaller pieces.",
            accepted: ["true"] },
          { id: "q2", number: 2, type: "true_false_notgiven",
            prompt: "All wildlife corridors are expensive bridges built over motorways.",
            accepted: ["false"] },
          { id: "q3", number: 3, type: "true_false_notgiven",
            prompt: "Corridors can help animals move to cooler areas as the climate warms.",
            accepted: ["true"] },
          { id: "q4", number: 4, type: "yes_no_notgiven",
            prompt: "The writer thinks the cost of corridors is too high to be worthwhile.",
            accepted: ["no"] },
          { id: "q5", number: 5, type: "sentence_completion", wordLimit: 2,
            prompt: "A wildlife corridor is a strip of natural ______ that connects two patches.",
            accepted: ["habitat"] },
          { id: "q6", number: 6, type: "sentence_completion", wordLimit: 1,
            prompt: "Small creatures can use ______ built under roads to cross safely.",
            accepted: ["tunnels"] },
          { id: "q7", number: 7, type: "single_choice",
            prompt: "According to the passage, corridors keep animal populations healthy by giving them:",
            options: [
              { value: "A", label: "more food and a wider choice of mates" },
              { value: "B", label: "protection from hunters" },
              { value: "C", label: "warmer places to sleep" },
            ],
            accepted: ["A"] },
          { id: "q8", number: 8, type: "short_answer", wordLimit: 4,
            prompt: "What may a corridor need from many different owners before it can be built?",
            accepted: ["agreement", "their agreement"] },
        ],
      },
    ],
  },
  {
    id: "gt-reading-008",
    skill: "reading",
    variant: "general-training",
    title: "GT Reading Practice — The History of the Bicycle",
    timeMinutes: 20,
    sections: [
      {
        id: "s1",
        name: "Section 3: General Reading",
        passageTitle: "The History of the Bicycle",
        passageParagraphs: [
          "The bicycle as we know it took almost a century to develop. The earliest version, built in Germany in 1817, had no pedals at all. Riders pushed themselves along the ground with their feet, and the machine was used mainly for fun by wealthy young men. It was heavy, uncomfortable and quickly went out of fashion.",
          "Pedals were added in the 1860s, attached directly to the front wheel. To go faster, makers built the front wheel larger and larger, producing the famous 'penny-farthing' with its enormous front wheel and tiny back one. These machines were fast but dangerous, since the rider sat high above the ground and could be thrown off easily.",
          "The breakthrough came in the 1880s with the 'safety bicycle', which had two wheels of equal size and a chain that drove the back wheel. This design was much steadier and could be ridden by almost anyone. When air-filled rubber tyres were added soon afterwards, the ride became far more comfortable, and cycling became hugely popular.",
          "The effects went beyond transport. For the first time, ordinary people could travel several miles cheaply and without a horse. The bicycle is often said to have given women in particular greater freedom of movement, and it remains one of the most efficient machines ever invented.",
        ],
        questions: [
          { id: "q1", number: 1, type: "true_false_notgiven",
            prompt: "The earliest bicycle had pedals attached to the front wheel.",
            accepted: ["false"] },
          { id: "q2", number: 2, type: "true_false_notgiven",
            prompt: "The penny-farthing was considered dangerous to ride.",
            accepted: ["true"] },
          { id: "q3", number: 3, type: "true_false_notgiven",
            prompt: "The safety bicycle had two wheels of equal size.",
            accepted: ["true"] },
          { id: "q4", number: 4, type: "sentence_completion", wordLimit: 2,
            prompt: "The first bicycle, built in 1817, had no ______ at all.",
            accepted: ["pedals"] },
          { id: "q5", number: 5, type: "sentence_completion", wordLimit: 1,
            prompt: "On the safety bicycle, a ______ drove the back wheel.",
            accepted: ["chain"] },
          { id: "q6", number: 6, type: "single_choice",
            prompt: "What made the ride much more comfortable after the safety bicycle appeared?",
            options: [
              { value: "A", label: "a larger front wheel" },
              { value: "B", label: "air-filled rubber tyres" },
              { value: "C", label: "a lighter metal frame" },
            ],
            accepted: ["B"] },
          { id: "q7", number: 7, type: "single_choice",
            prompt: "According to the passage, the bicycle is often said to have given greater freedom to:",
            options: [
              { value: "A", label: "wealthy young men" },
              { value: "B", label: "women in particular" },
              { value: "C", label: "factory owners" },
            ],
            accepted: ["B"] },
          { id: "q8", number: 8, type: "short_answer", wordLimit: 3,
            prompt: "In which country was the earliest version of the bicycle built?",
            accepted: ["Germany"] },
        ],
      },
    ],
  },
  {
    id: "gt-reading-009",
    skill: "reading",
    variant: "general-training",
    title: "GT Reading Practice — Community Gardens",
    timeMinutes: 20,
    sections: [
      {
        id: "s1",
        name: "Section 3: General Reading",
        passageTitle: "Community Gardens",
        passageParagraphs: [
          "A community garden is a single piece of land gardened by a group of people. In some, each member looks after a small plot of their own; in others, everyone works together and shares the harvest. Such gardens are often created on empty land in a city, turning a neglected space into something useful and green.",
          "The food grown is only one of the attractions. For people living in flats without a garden of their own, a shared plot is a chance to grow fresh vegetables and spend time outdoors. Gardeners frequently say that the work is relaxing and that being among plants helps them feel calmer after a busy day.",
          "Community gardens also bring people together. Members of different ages and backgrounds meet over the fences between their plots, swap seeds and advice, and often become friends. In neighbourhoods where people rarely speak to their neighbours, a garden can create a strong sense of belonging.",
          "Running a garden does require organisation. Someone must collect any fees, arrange the watering during dry spells, and decide what to do if a member stops looking after their plot. Despite these challenges, demand for plots is high, and in many cities people must join a waiting list before a space becomes free.",
        ],
        questions: [
          { id: "q1", number: 1, type: "true_false_notgiven",
            prompt: "In every community garden, members share all the food equally.",
            accepted: ["false"] },
          { id: "q2", number: 2, type: "true_false_notgiven",
            prompt: "Community gardens are often created on empty land in cities.",
            accepted: ["true"] },
          { id: "q3", number: 3, type: "true_false_notgiven",
            prompt: "Demand for garden plots is low in most cities.",
            accepted: ["false"] },
          { id: "q4", number: 4, type: "yes_no_notgiven",
            prompt: "The writer suggests that gardening can help people feel calmer.",
            accepted: ["yes"] },
          { id: "q5", number: 5, type: "sentence_completion", wordLimit: 2,
            prompt: "A community garden is a single piece of ______ gardened by a group.",
            accepted: ["land"] },
          { id: "q6", number: 6, type: "sentence_completion", wordLimit: 2,
            prompt: "In some gardens, members swap seeds and ______ over the fences.",
            accepted: ["advice"] },
          { id: "q7", number: 7, type: "single_choice",
            prompt: "According to the passage, a community garden can be especially valuable for people who:",
            options: [
              { value: "A", label: "live in flats without a garden" },
              { value: "B", label: "work as professional farmers" },
              { value: "C", label: "dislike spending time outdoors" },
            ],
            accepted: ["A"] },
          { id: "q8", number: 8, type: "short_answer", wordLimit: 3,
            prompt: "What must people often join before a plot becomes free?",
            accepted: ["a waiting list", "waiting list"] },
        ],
      },
    ],
  },
  {
    id: "gt-reading-010",
    skill: "reading",
    variant: "general-training",
    title: "GT Reading Practice — Public Drinking Fountains",
    timeMinutes: 20,
    sections: [
      {
        id: "s1",
        name: "Section 3: General Reading",
        passageTitle: "Public Drinking Fountains",
        passageParagraphs: [
          "Public drinking fountains were once a common sight in towns and cities. In the nineteenth century, many were built by charities to provide clean, free water at a time when disease often spread through dirty supplies. Some were grand structures of stone and iron, designed to be admired as well as used.",
          "During the twentieth century, however, large numbers of fountains were removed or left to fall into disrepair. As cheap bottled water became widely available, many people stopped relying on public taps, and councils saw little reason to maintain them. In some places, the old fountains disappeared almost entirely.",
          "Recently, attitudes have begun to change again. Concern about the waste created by plastic bottles has led several cities to install new fountains and bottle-filling points in parks, stations and shopping streets. Supporters argue that easy access to free water encourages people to carry a reusable bottle instead of buying a new plastic one each time they are thirsty.",
          "There are practical questions to solve. Fountains must be cleaned regularly to remain safe, and they can be expensive to install where no water pipe is nearby. Even so, many residents welcome their return, seeing them as a simple, healthy and environmentally friendly feature of a modern city.",
        ],
        questions: [
          { id: "q1", number: 1, type: "true_false_notgiven",
            prompt: "In the nineteenth century, some drinking fountains were built by charities.",
            accepted: ["true"] },
          { id: "q2", number: 2, type: "true_false_notgiven",
            prompt: "All public fountains were removed during the twentieth century.",
            accepted: ["false"] },
          { id: "q3", number: 3, type: "true_false_notgiven",
            prompt: "Concern about plastic waste has led some cities to install new fountains.",
            accepted: ["true"] },
          { id: "q4", number: 4, type: "sentence_completion", wordLimit: 3,
            prompt: "Nineteenth-century fountains provided clean, free water when disease often spread through ______.",
            accepted: ["dirty supplies"] },
          { id: "q5", number: 5, type: "sentence_completion", wordLimit: 3,
            prompt: "The spread of cheap ______ led many people to stop using public taps.",
            accepted: ["bottled water"] },
          { id: "q6", number: 6, type: "single_choice",
            prompt: "Supporters say new fountains encourage people to:",
            options: [
              { value: "A", label: "drink less water" },
              { value: "B", label: "carry a reusable bottle" },
              { value: "C", label: "visit parks more often" },
            ],
            accepted: ["B"] },
          { id: "q7", number: 7, type: "single_choice",
            prompt: "One practical problem with fountains mentioned in the passage is that they:",
            options: [
              { value: "A", label: "must be cleaned regularly to stay safe" },
              { value: "B", label: "make the streets too crowded" },
              { value: "C", label: "use electricity to cool the water" },
            ],
            accepted: ["A"] },
          { id: "q8", number: 8, type: "short_answer", wordLimit: 3,
            prompt: "Apart from parks and stations, where else have some cities installed new fountains?",
            accepted: ["shopping streets"] },
        ],
      },
    ],
  },
];

// Prefix each question id with its test id so question ids are globally unique
// across the whole reading test bank.
export const moreReadingTests: ReadingTest[] = rawReadingTests.map((test) => ({
  ...test,
  sections: test.sections.map((section) => ({
    ...section,
    questions: section.questions.map((q) => ({ ...q, id: `${test.id}-${q.id}` })),
  })),
}));
